---
- name: Provision terse customer static web server with caddy and nginx
  hosts: all
  become: yes
  vars_files:
    - ["roles/common/vars/family-{{ ansible_facts['os_family'] }}.yml"]
  roles:
    - role: common
    - role: debian-docker
    - role: debian-terse
    - role: debian-harden
