---
- name: Apply common, debian-docker roles to all targets
  hosts: docker
  become: yes
  vars_files:
    - ["roles/common/vars/family-{{ ansible_facts['os_family'] }}.yml"]
  roles:
    - role: common
    - role: debian-docker
