---
- name: Provision containerised web-server and reverse-proxy with TLS
  hosts: all
  become: yes
  vars_files:
    - ["roles/common/vars/family-{{ ansible_facts['os_family'] }}.yml"]
  roles:
    - role: common
    - role: debian-docker
    - role: debian-webserver
    - role: debian-harden
