---
- name: Harden security of all debian based targets
  hosts: all
  become: yes
  vars_files:
    - ["roles/common/vars/family-{{ ansible_facts['os_family'] }}.yml"]
  roles:
    - role: debian-harden
