---
- name: Provision getlegit.co.uk vps
  hosts: getlegit
  become: yes
  vars_files:
    - ["roles/common/vars/family-{{ ansible_facts['os_family'] }}.yml"]
  roles:
    - role: common
    - role: debian-docker
    # - role: debian-harden
  vars:
    docker_compose_volumes:
      - caddy_reverse_proxy_config
      - caddy_reverse_proxy_data
      - mariadb
      - nextcloud_data
      - nextcloud_html
      - strapi_terse
      - teamspeak
      - wp_edmunds
      - znc
    restore_dir: /srv/restore

  tasks:
    - name: Create docker network network1
      community.docker.docker_network:
        attachable: no
        internal: no
        name: network1
        scope: local
        state: present

    - name: Create docker-compose persistent volumes
      community.docker.docker_volume:
        recreate: never # !!! changing this could OVERWRITE existing volumes !!!
        state: present
        volume_name: "{{ item }}"
      loop: "{{ docker_compose_volumes }}"

    - name: Mount new teamspeak volume(s). Restore files from backup
      community.docker.docker_container:
        cleanup: yes
        command: sh -c 'tar -xvf /restore/backups.tar backups/volumes/teamspeak/ -C / --strip-components=3'
        command_handling: correct
        detach: no
        image: alpine:latest
        interactive: no
        keep_volumes: no
        name: copy_files
        pull: yes
        restart: no
        restart_policy: "no"
        state: started
        volumes:
          - "{{ restore_dir }}/:/restore/"
          - teamspeak:/var/ts3server

    - name: Mount new znc volume(s). Restore files from backup
      community.docker.docker_container:
        cleanup: yes
        command: sh -c 'tar -xvf /restore/backups.tar backups/volumes/znc/ -C / --strip-components=3'
        command_handling: correct
        detach: no
        image: alpine:latest
        interactive: no
        keep_volumes: no
        name: copy_files
        pull: yes
        restart: no
        restart_policy: "no"
        state: started
        volumes:
          - "{{ restore_dir }}/:/restore/"
          - znc:/znc-data

    - name: Mount new wordpress volume(s). Restore files from backup
      community.docker.docker_container:
        cleanup: yes
        command: sh -c 'tar -xvf /restore/backups.tar backups/volumes/wp_edmunds/ -C / --strip-components=3'
        command_handling: correct
        detach: no
        image: alpine:latest
        interactive: no
        keep_volumes: no
        name: copy_files
        pull: yes
        restart: no
        restart_policy: "no"
        state: started
        volumes:
          - "{{ restore_dir }}/:/restore/"
          - wp_edmunds:/var/www/html

