---
- name: Provision getlegit.co.uk vps
  hosts: getlegit
  become: yes
  vars_files:
    - ["roles/common/vars/family-{{ ansible_facts['os_family'] }}.yml"]
  roles:
    - role: common
    - role: debian-docker
    # - role: debian-harden
  vars:
    docker_compose_volumes:
      - caddy_reverse_proxy_config
      - caddy_reverse_proxy_data
      - mariadb
      - nextcloud_data
      - nextcloud_html
      - strapi_terse
      - teamspeak
      - wp_edmunds
      - znc

  tasks:
    - name: Create docker network network1
      community.docker.docker_network:
        attachable: no
        internal: no
        name: network1
        scope: local
        state: present

    - name: Create docker-compose persistent volumes
      community.docker.docker_volume:
        recreate: never # !!! changing this could OVERWRITE existing volumes !!!
        state: present
        volume_name: "{{ item }}"
      loop: "{{ docker_compose_volumes }}"

