---
- name: Transitionary getlegit update playbook. (make fully managed on release of debian 11)
  hosts: getlegit
  become: yes
  roles:
    - role: common
    - role: debian-docker
    - role: debian-harden
  vars:
    sudo_group: sudo
    compose_parent_dir: /srv/getlegit-docker-compose
    compose_services:
      - nginx/getlegit
      - nginx/hatch
      - nginx/maljo
      - nginx/terse
      - teamspeak
      - wp_edmunds
      - znc
      - strapi_terse
      - nextcloud
      - caddy_reverse_proxy

  handlers:
    - name: Reboot target
      reboot:

  tasks:
    - name: Install pip for python3
      apt:
        update_cache: yes
        state: latest
        install_recommends: yes
        name: python3-pip

    - name: Install docker module pip dependencies
      pip:
        state: latest
        name:
          - PyYAML
          - docker-compose
          - docker

    - name: Stop all docker-compose services
      community.docker.docker_compose:
        project_src: "{{ compose_parent_dir }}/{{ item }}"
        state: present
        stopped: yes
      loop: "{{ compose_services }}"
      register: output

    - ansible.builtin.debug:
        var: output

    - name: Stop mariadb docker-compose service
      community.docker.docker_compose:
        project_src: "{{ compose_parent_dir }}/mariadb"
        state: present
        stopped: yes
      register: output

    - ansible.builtin.debug:
        var: output

    - name: Pull fresh mariadb image, start mariadb docker-compose service
      community.docker.docker_compose:
        pull: yes
        project_src: "{{ compose_parent_dir }}/mariadb"
        state: present
        stopped: no
      register: output

    - ansible.builtin.debug:
        var: output

    - name: Pull fresh images, start all docker-compose services
      community.docker.docker_compose:
        pull: yes
        project_src: "{{ compose_parent_dir }}/{{ item }}"
        state: present
        stopped: no
      loop: "{{ compose_services }}"
      register: output

    - ansible.builtin.debug:
        var: output

    - name: Remove redundant docker images
      community.docker.docker_prune:
        images: yes

    - name: Perform safe apt upgrade
      apt:
        update_cache: yes
        state: latest
        install_recommends: yes
        upgrade: safe
      notify:
        - Reboot target
