---
- name: Transitionary getlegit update playbook. (make fully managed on release of debian 11)
  hosts: getlegit
  become: yes
  roles:
    - role: common
    - role: debian-docker
    - role: debian-harden
  vars_files: ./vars/getlegit.yml

  handlers:
    - name: Reboot target
      reboot:

  tasks:
    - name: Generate ssh key for use with github
      community.crypto.openssh_keypair:
        comment: github/robinedmunds
        force: no # do NOT overwrite existing key
        group: docker
        mode: 0640
        owner: ansible
        path: /srv/keys/id_ed25519
        regenerate: never # do NOT overwrite existing key
        state: present
        type: ed25519

    - name: Clone robinedmunds/getlegit-docker-compose repo
      ansible.builtin.git:
        accept_newhostkey: yes
        update: yes
        clone: yes
        key_file: /srv/keys/id_ed25519
        remote: remote
        repo: git@github.com:robinedmunds/getlegit-docker-compose.git
        dest: "{{ compose_parent_dir }}"

    - name: Set ownership of getlegit-docker-compose repo files
      ansible.builtin.file:
        group: docker
        mode: 0664
        owner: robin
        path: "{{ compose_parent_dir }}"
        recurse: yes
        state: directory

    - name: Set nextcloud cronjob script to executable
      ansible.builtin.file:
        mode: 0774
        path: "{{ compose_parent_dir }}"/nextcloud/cron.sh

    # TODO: add nextcloud cronjob to user, robin

    - name: Stop all docker-compose services
      community.docker.docker_compose:
        project_src: "{{ compose_parent_dir }}/{{ item }}"
        state: present
        stopped: yes
      loop: "{{ compose_services }}"
      register: output

    - ansible.builtin.debug:
        var: output

    - name: Stop mariadb docker-compose service
      community.docker.docker_compose:
        project_src: "{{ compose_parent_dir }}/mariadb"
        state: present
        stopped: yes
      register: output

    - ansible.builtin.debug:
        var: output

    - name: Pull fresh mariadb image, start mariadb docker-compose service
      community.docker.docker_compose:
        pull: yes
        project_src: "{{ compose_parent_dir }}/mariadb"
        state: present
        stopped: no
      register: output

    - ansible.builtin.debug:
        var: output

    - name: Pull fresh images, start all docker-compose services
      community.docker.docker_compose:
        pull: yes
        project_src: "{{ compose_parent_dir }}/{{ item }}"
        state: present
        stopped: no
      loop: "{{ compose_services }}"
      register: output

    - ansible.builtin.debug:
        var: output

    # TODO: occ db:add-missing-indices

    - name: Remove redundant docker images
      community.docker.docker_prune:
        images: yes

    - name: Perform safe apt upgrade
      apt:
        update_cache: yes
        state: latest
        install_recommends: yes
        upgrade: safe
      notify:
        - Reboot target
