---
# vars file for debian-common
- essential_pkgs:
  - debian:
    [
      "sudo",
      "less",
      "vim",
      "nano",
      "tree",
      "tmux",
      "htop",
      "lshw",
      "lsb-release",
      "curl",
      "wget",
      "git",
      "gnupg",
      "zip",
      "pigz",
      "python3-pip"
    ]
  - fedora:
      [
        "sudo",
        "less",
        "vim",
        "nano",
        "tree",
        "tmux",
        "htop",
        "lshw",
        "redhat-lsb-core",
        "curl",
        "wget",
        "git",
        "gnupg",
        "zip",
        "pigz",
        "python3-pip"
      ]
