# tasks file for debian-terse
- name: Install pip for python3
  apt:
    update_cache: yes
    state: latest
    install_recommends: yes
    name: python3-pip

- name: Install docker module pip dependencies
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - PyYAML
    - docker

- name: Create dir /srv/www/*
  file:
    owner: root
    group: docker
    path: "/srv/www/{{ primary_url }}/"
    state: directory

- name: Copy html template
  copy:
    dest: "/srv/www/{{ primary_url }}/index.html"
    mode: 0775
    owner: root
    group: docker
    src: ../files/index.html

- name: Create dir /srv/docker/web
  file:
    owner: root
    group: docker
    path: /srv/docker/web
    state: directory

- name: Generate nginx, caddy docker-compose file from template
  template:
    dest: /srv/docker/web/docker-compose.yml
    mode: 0664
    owner: root
    group: docker
    src: ../templates/docker-compose/web.jinja2

- name: Generate Caddyfile from template
  template:
    dest: /srv/docker/web/Caddyfile
    mode: 0664
    owner: root
    group: docker
    src: ../templates/Caddyfile.jinja2

- name: Start web services with docker-compose
  community.docker.docker_compose:
    project_src: /srv/docker/web/
    pull: yes
    remove_orphans: yes
    state: present
