- name: Perform safe apt upgrade
  apt:
    update_cache: yes
    state: latest
    install_recommends: yes
    upgrade: safe
  notify:
    - Reboot target

- name: Install list of essential apt pkgs
  apt:
    update_cache: yes
    state: latest
    install_recommends: yes
    name: "{{ essential_pkgs['debian'] }}"
