- name: Remove previous docker installs
  apt:
    purge: yes
    state: absent
    name: "{{ item }}"
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Install docker dependencies
  apt:
    update_cache: yes
    install_recommends: yes
    state: latest
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Download official docker repo gpg key
  get_url:
    dest: /tmp/docker-repo-gpg.key
    url: https://download.docker.com/linux/debian/gpg
    validate_certs: yes # https

- name: Install official docker repo gpg key
  shell:
    cmd: sudo gpg --dearmor --import /tmp/docker-repo-gpg.key -o /usr/share/keyrings/docker-archive-keyring.gpg
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add official docker repo to sources.list.d
  apt_repository:
    state: present
    update_cache: yes
    filename: docker
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable
    validate_certs: yes # https

- name: Install docker from docker repo
  apt:
    update_cache: yes
    install_recommends: yes
    state: latest
    name: "{{ item }}"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Enable and start docker systemd unit
  service:
    name: docker
    enabled: yes
    state: started

- name: Add docker admins to docker group
  user:
    append: yes
    groups: docker
    name: "{{ item }}"

  loop: docker_admins
