- name: Install pip for python3
  apt:
    update_cache: yes
    state: latest
    install_recommends: yes
    name: python3-pip

- name: Install docker module pip dependencies
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - PyYAML
    - docker-compose
    - docker
