---
# vars file for debian-common
essential_pkgs:
  debian:
    [
      "sudo",
      "less",
      "neovim",
      "nano",
      "tree",
      "tmux",
      "htop",
      "lshw",
      "lsb-release",
      "curl",
      "wget",
      "git",
      "gnupg",
      "zip",
      "pigz",
      "python3-pip",
      "rsync"
    ]
  fedora:
    [
      "sudo",
      "less",
      "neovim",
      "nano",
      "tree",
      "tmux",
      "htop",
      "lshw",
      "curl",
      "wget",
      "git",
      "gnupg",
      "zip",
      "pigz",
      "python3-pip",
      "rsync"
    ]
