- name: Perform safe apt upgrade
  apt:
    update_cache: yes
    state: latest
    install_recommends: yes
    upgrade: safe

- name: Install list of essential apt pkgs
  apt:
    update_cache: yes
    state: latest
    install_recommends: yes
    name: "{{ item }}"
  loop: "{{ essential_pkgs }}"
