# tasks file for debian-common
- name: Apt upgrade system and install essential pkgs
  import_playbook: apt.yml

- name: Symlink /usr/bin/python to python3
  import_playbook: link_python3.yml

- name: Create sudo user robin
  import_playbook: robin.yml

- name: Set remote hostname to inventory alias
  import_playbook: set_hostname.yml

- name: Lock root user, create recovery account, whoops
  import_playbook: lock_root.yml

- name: Reboot target
  import_playbook: reboot.yml
