# tasks file for debian-common
- name: Set remote hostname to inventory alias
  import_tasks: set_hostname.yml

- name: Apt upgrade system and install essential pkgs
  import_tasks: apt.yml

- name: Create recovery account (whoops), lock root
  import_tasks: lock_root.yml

- name: Create sudo user robin
  import_tasks: robin.yml
