# tasks file for debian-common
- name: Apt upgrade system and install essential pkgs
  import_tasks: apt.yml
  vars:
    essential_pkgs:
      [
        "sudo",
        "less",
        "vim",
        "nano",
        "tree",
        "tmux",
        "htop",
        "lshw",
        "lsb-release",
        "curl",
        "wget",
        "git",
        "gnupg",
        "zip",
        "pigz"
      ]

- name: Symlink /usr/bin/python to python3
  import_tasks: link_python3.yml

- name: Create sudo user robin
  import_tasks: robin.yml

- name: Set remote hostname to inventory alias
  import_tasks: set_hostname.yml

- name: Lock root user, create recovery account, whoops
  import_tasks: lock_root.yml

- name: Reboot target
  import_tasks: reboot.yml
