---
- name: Set hostname of target to inventory alias
  become: yes
  tasks:
    - name: Set hostname of target to inventory alias
      hostname:
        use: systemd
        name: "{{ inventory_hostname }}"

    - name: Generate /etc/hosts from template
      template:
        src: ../templates/hosts.j2
        dest: /etc/hosts
        force: yes
        group: root
        owner: root
        mode: 0644
